### PR TITLE
Check if projects/languages/OSes/editors are present in Wakatime response

### LINKED ISSUE #391: wakatime: Error when `projects`/`languages`/`editors`/`operating_systems` is `null`
[Relevant config](https://github.com/cherryblossom000/cherryblossom000/blob/main/.github/workflows/metrics.yml):

```yml
name: metrics
# ...
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
    - uses: lowlighter/metrics@latest
      with:
        # ...
        plugin_wakatime: true
        plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
        plugin_wakatime_sections: time, languages, languages-graphs, editors, os
        plugin_wakatime_url: https://wakapi.dev
        plugin_wakatime_user: cherryblossom # using default of current doesn't work
```

[Error](https://github.com/cherryblossom000/cherryblossom000/runs/2838256728?check_suite_focus=true#step:2:427):

```
metrics/compute/cherryblossom000 > 1 errors !
[
  {
    name: 'wakatime',
    result: {
      error: {
        message: 'An error occured',
        instance: TypeError: Cannot read property 'map' of null
            at Object.default [as wakatime] (file:///metrics/source/plugins/wakatime/index.mjs:30:31)
            at processTicksAndRejections (node:internal/process/task_queues:94:5)
            at async file:///metrics/source/plugins/core/index.mjs:46:30
            at async Promise.all (index 12)
            at async metrics (file:///metrics/source/app/metrics/index.mjs:61:22)
            at async file:///metrics/source/app/action/index.mjs:290:24
      }
    }
  }
]
```

I'm not sure about Wakatime, but [Wakapi](https://wakapi.dev/) allows you to hide your projects, languages, editors, and OSes from the API:

Screenshot of Wakapi ‘Public Data’ settings, showing that you can toggle ‘Share projects’, ‘Share languages’, ‘Share editors’, ‘Share operating systems’, ‘Share machines’, and ‘Share project labels’ for the endpoint `/api/v1/users/{user}/stats/{range}`.

The error occurs here:

https://github.com/lowlighter/metrics/blob/8b4bf0c8c425bef12134f7ab39ef6ccf50dbc3e9/source/plugins/wakatime/index.mjs#L30

because `stats.projects` is null.

### PR DESCRIPTION
**Pull request by cherryblossom000**
Fixes #391

### CODE REVIEW

File: source/plugins/wakatime/index.mjs [hunk 1]
```diff
@@ -27,10 +27,10 @@ export default async function({login, q, imports, data, account}, {enabled = fal
...
-      os:stats.operating_systems.map(({name, percent, total_seconds:total}) => ({name, percent:percent / 100, total})).sort((a, b) => b.percent - a.percent).slice(0, limit),
-      editors:stats.editors.map(({name, percent, total_seconds:total}) => ({name, percent:percent / 100, total})).sort((a, b) => b.percent - a.percent).slice(0, limit),
+      projects:stats.projects && stats.projects.map(({name, percent, total_seconds:total}) => ({name, percent:percent / 100, total})).sort((a, b) => b.percent - a.percent).slice(0, limit),
+      languages:stats.languages && stats.languages.map(({name, percent, total_seconds:total}) => ({name, percent:percent / 100, total})).sort((a, b) => b.percent - a.percent).slice(0, limit),
+      os:stats.operating_systems && stats.operating_systems.map(({name, percent, total_seconds:total}) => ({name, percent:percent / 100, total})).sort((a, b) => b.percent - a.percent).slice(0, limit),
+      editors:stats.editors && stats.editors.map(({name, percent, total_seconds:total}) => ({name, percent:percent / 100, total})).sort((a, b) => b.percent - a.percent).slice(0, limit),
```
Comment (spenserblack) [inline source/plugins/wakatime/index.mjs:33]: You might want to use the `??` operator instead of `&&`, which checks *specifically* for `null`/`undefined` instead of whether it is falsy. Since `??` is frequently used in  this project, I think it might be preferred.
```suggestion
      projects:stats.projects ?? stats.projects.map(({name, percent, total_seconds:total}) => ({name, percent:percent / 100, total})).sort((a, b) => b.percent - a.percent).slice(0, limit),
      languages:stats.languages ?? stats.languages.map(({name, percent, total_seconds:total}) => ({name, percent:percent / 100, total})).sort((a, b) => b.percent - a.percent).slice(0, limit),
      os:stats.operating_systems ?? stats.operating_systems.map(({name, percent, total_seconds:total}) => ({name, percent:percent / 100, total})).sort((a, b) => b.percent - a.percent).slice(0, limit),
      editors:stats.editors ?? stats.editors.map(({name, percent, total_seconds:total}) => ({name, percent:percent / 100, total})).sort((a, b) => b.percent - a.percent).slice(0, limit),
```

Comment (spenserblack) [inline source/plugins/wakatime/index.mjs:33]: Given the rest of the code I've seen in this project, I think this is the preferred style.
```suggestion
      projects:stats.projects?.map(({name, percent, total_seconds:total}) => ({name, percent:percent / 100, total})).sort((a, b) => b.percent - a.percent).slice(0, limit),
      languages:stats.languages?.map(({name, percent, total_seconds:total}) => ({name, percent:percent / 100, total})).sort((a, b) => b.percent - a.percent).slice(0, limit),
      os:stats.operating_systems?.map(({name, percent, total_seconds:total}) => ({name, percent:percent / 100, total})).sort((a, b) => b.percent - a.percent).slice(0, limit),
      editors:stats.editors?.map(({name, percent, total_seconds:total}) => ({name, percent:percent / 100, total})).sort((a, b) => b.percent - a.percent).slice(0, limit),
```

Comment (cherryblossom000) [reply source/plugins/wakatime/index.mjs]: Thanks, didn't realise we were targeting Node.js 14.

**Review by lowlighter — APPROVED** [review]

**Comment by lowlighter** [comment]
Thanks a lot!
