### PR TITLE
fix(plugins/languages): skip merge commits from recent analysis

### LINKED ISSUE #502: Merge commit not skipped in language stats
I found random language 'TCL' in my language stats this morning:
image

I was thinking this was an issue on my end but found this merge commit yesterday:
image
It added a [666 SLOC file](https://github.com/github/linguist/blob/f56a04e0d6d428ce2b2f3f02e7fd9918b9bbc572/samples/Tcl/init.tcl.in) (https://github.com/github/linguist/commit/f56a04e0d6d428ce2b2f3f02e7fd9918b9bbc572), which metrics doesn't seem to have skipped.

### PR DESCRIPTION
**Pull request by lowlighter**
Skip merge commits (assuming parents > 2) from recent language analysis 

Closes #502

### CODE REVIEW

**Review by spenserblack — APPROVED** [review]

File: source/plugins/languages/analyzers.mjs [hunk 1]
```diff
@@ -75,9 +75,11 @@ export async function recent({login, data, imports, rest, account}, {skipped = [
         .flatMap(({payload}) => payload.commits)
         .filter(({author}) => data.shared["commits.authoring"].filter(authoring => author?.email?.toLocaleLowerCase().includes(authoring)||author?.name?.toLocaleLowerCase().includes(authoring)).length)
         .map(commit => commit.url)
-        .map(async commit => (await rest.request(commit)).data.files),
-    ),
+        .map(async commit => (await rest.request(commit)).data),
+    )
   ]
+  .filter(({parents}) => parents.length <= 1)
```
Comment (Nixinova) [inline source/plugins/languages/analyzers.mjs:81]: Apparently the `parents` key is not always there:
image
